name = "NameGen"
uuid = "a92c3cb4-10a9-4fc0-97cd-a00a57b668ac"
repo = "https://github.com/mtanneau/NameGen.jl.git"
version = "0.1.0"

[deps]
InlineStrings = "842dd82b-1e85-43dc-bf29-5d0ee9dffc48"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
