name = "Geppetto"
uuid = "7616020f-7d25-45ac-879d-3d4711576aab"
repo = "https://github.com/mtanneau/Geppetto.jl.git"
version = "0.1.0"

[deps]
InlineStrings = "842dd82b-1e85-43dc-bf29-5d0ee9dffc48"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
InlineStrings = "1"
julia = "1.6"
